### PR TITLE
Fix typo in url construction

### PR DESCRIPTION
**Pull request by harterrt**

### CODE REVIEW

**Comment by harterrt** [comment]
@jklukas - I can't seem to add you as a reviewer. Can you PTAL?

**Review by jklukas — COMMENTED** [review]
To my knowledge, there should be a trailing `.git` for both https and ssh paths. Can you give me an example of how you're invoking this and what error you're getting?

**Comment by harterrt** [comment]
You're right, there does need to be a `.git` suffix. But, the `.git` suffix is already included in `REPO_NAME` when it's generated. 

E.g. when I run `git remote get-url --push origin | awk -F/ '{print $NF}'` locally in a git repo, I get something like: `<repo_name>.git`

**Comment by jklukas** [comment]
Weird, I don't get the `.git` when I try `git remote get-url --push origin` in a few repos. This may be something that can be configured either way.

How about we update the following line instead:

    REPO_NAME=$(git remote get-url --push origin | awk -F/ '{print $NF}' | sed 's/\.git$//')

That should strip off the `.git` if it exists, and then the existing code should work in either case.

**Comment by harterrt** [comment]
SGTM. Tested locally and that appears to work. Thanks!

**Comment by jklukas** [comment]
> SGTM. Tested locally and that appears to work. Thanks!

If you want to update this PR to match, I'd be happy to merge.

**Comment by harterrt** [comment]
Will do. 

Out of curiosity, what do you see when you run `git remote get-url --push origin`? Are your local repositories configured with push urls without the `.git` suffixes?

**Comment by jklukas** [comment]
I get `https://github.com/jklukas/gcp-ingestion`. I do not know why.

**Comment by allamand** [comment]
hello, I also had a double .git when using the script.
Do you think it is possible to make uses of Github labels to trigger the script when apply on server level ?

**Comment by jklukas** [comment]
The double `.git` problem should be fixed now via #6.

**Comment by jklukas** [comment]
>  Do you think it is possible to make uses of Github labels to trigger the script when apply on server level?

I'd be interested to see an issue written up to describe this use case in more detail.

**Pull request closed without merging**
